/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student.index'
import { Route as AuthenticatedStudentAssignmentsRouteImport } from './routes/_authenticated/student.assignments'
import { Route as AuthenticatedStudentBrowseRouteImport } from './routes/_authenticated/student.browse'
import { Route as AuthenticatedStudentMasteryRouteImport } from './routes/_authenticated/student.mastery'
import { Route as AuthenticatedStudentTutorRouteImport } from './routes/_authenticated/student.tutor'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher.index'
import { Route as AuthenticatedTeacherAnalyticsRouteImport } from './routes/_authenticated/teacher.analytics'
import { Route as AuthenticatedTeacherStudentsRouteImport } from './routes/_authenticated/teacher.students'
import { Route as AuthenticatedStudentCoursesIndexRouteImport } from './routes/_authenticated/student.courses.index'
import { Route as AuthenticatedStudentCoursesCourseIdRouteImport } from './routes/_authenticated/student.courses.$courseId'
import { Route as AuthenticatedStudentQuizQuizIdRouteImport } from './routes/_authenticated/student.quiz.$quizId'
import { Route as AuthenticatedTeacherCoursesIndexRouteImport } from './routes/_authenticated/teacher.courses.index'
import { Route as AuthenticatedTeacherCoursesCourseIdRouteImport } from './routes/_authenticated/teacher.courses.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentAssignmentsRoute =
  AuthenticatedStudentAssignmentsRouteImport.update({
    id: '/student/assignments',
    path: '/student/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentBrowseRoute =
  AuthenticatedStudentBrowseRouteImport.update({
    id: '/student/browse',
    path: '/student/browse',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentMasteryRoute =
  AuthenticatedStudentMasteryRouteImport.update({
    id: '/student/mastery',
    path: '/student/mastery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentTutorRoute =
  AuthenticatedStudentTutorRouteImport.update({
    id: '/student/tutor',
    path: '/student/tutor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherAnalyticsRoute =
  AuthenticatedTeacherAnalyticsRouteImport.update({
    id: '/teacher/analytics',
    path: '/teacher/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherStudentsRoute =
  AuthenticatedTeacherStudentsRouteImport.update({
    id: '/teacher/students',
    path: '/teacher/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCoursesIndexRoute =
  AuthenticatedStudentCoursesIndexRouteImport.update({
    id: '/student/courses/',
    path: '/student/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCoursesCourseIdRoute =
  AuthenticatedStudentCoursesCourseIdRouteImport.update({
    id: '/student/courses/$courseId',
    path: '/student/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentQuizQuizIdRoute =
  AuthenticatedStudentQuizQuizIdRouteImport.update({
    id: '/student/quiz/$quizId',
    path: '/student/quiz/$quizId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesIndexRoute =
  AuthenticatedTeacherCoursesIndexRouteImport.update({
    id: '/teacher/courses/',
    path: '/teacher/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesCourseIdRoute =
  AuthenticatedTeacherCoursesCourseIdRouteImport.update({
    id: '/teacher/courses/$courseId',
    path: '/teacher/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/student/assignments': typeof AuthenticatedStudentAssignmentsRoute
  '/student/browse': typeof AuthenticatedStudentBrowseRoute
  '/student/mastery': typeof AuthenticatedStudentMasteryRoute
  '/student/tutor': typeof AuthenticatedStudentTutorRoute
  '/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRoute
  '/student/quiz/$quizId': typeof AuthenticatedStudentQuizQuizIdRoute
  '/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRoute
  '/student/courses/': typeof AuthenticatedStudentCoursesIndexRoute
  '/teacher/courses/': typeof AuthenticatedTeacherCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/student/assignments': typeof AuthenticatedStudentAssignmentsRoute
  '/student/browse': typeof AuthenticatedStudentBrowseRoute
  '/student/mastery': typeof AuthenticatedStudentMasteryRoute
  '/student/tutor': typeof AuthenticatedStudentTutorRoute
  '/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRoute
  '/student/quiz/$quizId': typeof AuthenticatedStudentQuizQuizIdRoute
  '/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRoute
  '/student/courses': typeof AuthenticatedStudentCoursesIndexRoute
  '/teacher/courses': typeof AuthenticatedTeacherCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/student/assignments': typeof AuthenticatedStudentAssignmentsRoute
  '/_authenticated/student/browse': typeof AuthenticatedStudentBrowseRoute
  '/_authenticated/student/mastery': typeof AuthenticatedStudentMasteryRoute
  '/_authenticated/student/tutor': typeof AuthenticatedStudentTutorRoute
  '/_authenticated/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/_authenticated/teacher/students': typeof AuthenticatedTeacherStudentsRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRoute
  '/_authenticated/student/quiz/$quizId': typeof AuthenticatedStudentQuizQuizIdRoute
  '/_authenticated/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRoute
  '/_authenticated/student/courses/': typeof AuthenticatedStudentCoursesIndexRoute
  '/_authenticated/teacher/courses/': typeof AuthenticatedTeacherCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/profile'
    | '/student/assignments'
    | '/student/browse'
    | '/student/mastery'
    | '/student/tutor'
    | '/teacher/analytics'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
    | '/student/courses/$courseId'
    | '/student/quiz/$quizId'
    | '/teacher/courses/$courseId'
    | '/student/courses/'
    | '/teacher/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/profile'
    | '/student/assignments'
    | '/student/browse'
    | '/student/mastery'
    | '/student/tutor'
    | '/teacher/analytics'
    | '/teacher/students'
    | '/student'
    | '/teacher'
    | '/student/courses/$courseId'
    | '/student/quiz/$quizId'
    | '/teacher/courses/$courseId'
    | '/student/courses'
    | '/teacher/courses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/profile'
    | '/_authenticated/student/assignments'
    | '/_authenticated/student/browse'
    | '/_authenticated/student/mastery'
    | '/_authenticated/student/tutor'
    | '/_authenticated/teacher/analytics'
    | '/_authenticated/teacher/students'
    | '/_authenticated/student/'
    | '/_authenticated/teacher/'
    | '/_authenticated/student/courses/$courseId'
    | '/_authenticated/student/quiz/$quizId'
    | '/_authenticated/teacher/courses/$courseId'
    | '/_authenticated/student/courses/'
    | '/_authenticated/teacher/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/assignments': {
      id: '/_authenticated/student/assignments'
      path: '/student/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/browse': {
      id: '/_authenticated/student/browse'
      path: '/student/browse'
      fullPath: '/student/browse'
      preLoaderRoute: typeof AuthenticatedStudentBrowseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/mastery': {
      id: '/_authenticated/student/mastery'
      path: '/student/mastery'
      fullPath: '/student/mastery'
      preLoaderRoute: typeof AuthenticatedStudentMasteryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/tutor': {
      id: '/_authenticated/student/tutor'
      path: '/student/tutor'
      fullPath: '/student/tutor'
      preLoaderRoute: typeof AuthenticatedStudentTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/analytics': {
      id: '/_authenticated/teacher/analytics'
      path: '/teacher/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof AuthenticatedTeacherAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/students': {
      id: '/_authenticated/teacher/students'
      path: '/teacher/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/courses/': {
      id: '/_authenticated/student/courses/'
      path: '/student/courses'
      fullPath: '/student/courses/'
      preLoaderRoute: typeof AuthenticatedStudentCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/courses/$courseId': {
      id: '/_authenticated/student/courses/$courseId'
      path: '/student/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/quiz/$quizId': {
      id: '/_authenticated/student/quiz/$quizId'
      path: '/student/quiz/$quizId'
      fullPath: '/student/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedStudentQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/courses/': {
      id: '/_authenticated/teacher/courses/'
      path: '/teacher/courses'
      fullPath: '/teacher/courses/'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/courses/$courseId': {
      id: '/_authenticated/teacher/courses/$courseId'
      path: '/teacher/courses/$courseId'
      fullPath: '/teacher/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStudentAssignmentsRoute: typeof AuthenticatedStudentAssignmentsRoute
  AuthenticatedStudentBrowseRoute: typeof AuthenticatedStudentBrowseRoute
  AuthenticatedStudentMasteryRoute: typeof AuthenticatedStudentMasteryRoute
  AuthenticatedStudentTutorRoute: typeof AuthenticatedStudentTutorRoute
  AuthenticatedTeacherAnalyticsRoute: typeof AuthenticatedTeacherAnalyticsRoute
  AuthenticatedTeacherStudentsRoute: typeof AuthenticatedTeacherStudentsRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedStudentCoursesCourseIdRoute: typeof AuthenticatedStudentCoursesCourseIdRoute
  AuthenticatedStudentQuizQuizIdRoute: typeof AuthenticatedStudentQuizQuizIdRoute
  AuthenticatedTeacherCoursesCourseIdRoute: typeof AuthenticatedTeacherCoursesCourseIdRoute
  AuthenticatedStudentCoursesIndexRoute: typeof AuthenticatedStudentCoursesIndexRoute
  AuthenticatedTeacherCoursesIndexRoute: typeof AuthenticatedTeacherCoursesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStudentAssignmentsRoute: AuthenticatedStudentAssignmentsRoute,
  AuthenticatedStudentBrowseRoute: AuthenticatedStudentBrowseRoute,
  AuthenticatedStudentMasteryRoute: AuthenticatedStudentMasteryRoute,
  AuthenticatedStudentTutorRoute: AuthenticatedStudentTutorRoute,
  AuthenticatedTeacherAnalyticsRoute: AuthenticatedTeacherAnalyticsRoute,
  AuthenticatedTeacherStudentsRoute: AuthenticatedTeacherStudentsRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  AuthenticatedStudentCoursesCourseIdRoute:
    AuthenticatedStudentCoursesCourseIdRoute,
  AuthenticatedStudentQuizQuizIdRoute: AuthenticatedStudentQuizQuizIdRoute,
  AuthenticatedTeacherCoursesCourseIdRoute:
    AuthenticatedTeacherCoursesCourseIdRoute,
  AuthenticatedStudentCoursesIndexRoute: AuthenticatedStudentCoursesIndexRoute,
  AuthenticatedTeacherCoursesIndexRoute: AuthenticatedTeacherCoursesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
