/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedStudentMasteryRouteImport } from './routes/_authenticated/student.mastery'
import { Route as AuthenticatedStudentTutorRouteImport } from './routes/_authenticated/student.tutor'
import { Route as AuthenticatedTeacherAnalyticsRouteImport } from './routes/_authenticated/teacher.analytics'
import { Route as AuthenticatedTeacherCoursesRouteImport } from './routes/_authenticated/teacher.courses'
import { Route as AuthenticatedStudentCoursesCourseIdRouteImport } from './routes/_authenticated/student.courses.$courseId'
import { Route as AuthenticatedStudentQuizQuizIdRouteImport } from './routes/_authenticated/student.quiz.$quizId'
import { Route as AuthenticatedTeacherCoursesCourseIdRouteImport } from './routes/_authenticated/teacher.courses.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentMasteryRoute =
  AuthenticatedStudentMasteryRouteImport.update({
    id: '/mastery',
    path: '/mastery',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentTutorRoute =
  AuthenticatedStudentTutorRouteImport.update({
    id: '/tutor',
    path: '/tutor',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedTeacherAnalyticsRoute =
  AuthenticatedTeacherAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherCoursesRoute =
  AuthenticatedTeacherCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedStudentCoursesCourseIdRoute =
  AuthenticatedStudentCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentQuizQuizIdRoute =
  AuthenticatedStudentQuizQuizIdRouteImport.update({
    id: '/quiz/$quizId',
    path: '/quiz/$quizId',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedTeacherCoursesCourseIdRoute =
  AuthenticatedTeacherCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedTeacherCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/student/mastery': typeof AuthenticatedStudentMasteryRoute
  '/student/tutor': typeof AuthenticatedStudentTutorRoute
  '/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/teacher/courses': typeof AuthenticatedTeacherCoursesRouteWithChildren
  '/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRoute
  '/student/quiz/$quizId': typeof AuthenticatedStudentQuizQuizIdRoute
  '/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/student/mastery': typeof AuthenticatedStudentMasteryRoute
  '/student/tutor': typeof AuthenticatedStudentTutorRoute
  '/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/teacher/courses': typeof AuthenticatedTeacherCoursesRouteWithChildren
  '/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRoute
  '/student/quiz/$quizId': typeof AuthenticatedStudentQuizQuizIdRoute
  '/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/_authenticated/student/mastery': typeof AuthenticatedStudentMasteryRoute
  '/_authenticated/student/tutor': typeof AuthenticatedStudentTutorRoute
  '/_authenticated/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/_authenticated/teacher/courses': typeof AuthenticatedTeacherCoursesRouteWithChildren
  '/_authenticated/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRoute
  '/_authenticated/student/quiz/$quizId': typeof AuthenticatedStudentQuizQuizIdRoute
  '/_authenticated/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/student'
    | '/teacher'
    | '/student/mastery'
    | '/student/tutor'
    | '/teacher/analytics'
    | '/teacher/courses'
    | '/student/courses/$courseId'
    | '/student/quiz/$quizId'
    | '/teacher/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/student'
    | '/teacher'
    | '/student/mastery'
    | '/student/tutor'
    | '/teacher/analytics'
    | '/teacher/courses'
    | '/student/courses/$courseId'
    | '/student/quiz/$quizId'
    | '/teacher/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/student'
    | '/_authenticated/teacher'
    | '/_authenticated/student/mastery'
    | '/_authenticated/student/tutor'
    | '/_authenticated/teacher/analytics'
    | '/_authenticated/teacher/courses'
    | '/_authenticated/student/courses/$courseId'
    | '/_authenticated/student/quiz/$quizId'
    | '/_authenticated/teacher/courses/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/mastery': {
      id: '/_authenticated/student/mastery'
      path: '/mastery'
      fullPath: '/student/mastery'
      preLoaderRoute: typeof AuthenticatedStudentMasteryRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/tutor': {
      id: '/_authenticated/student/tutor'
      path: '/tutor'
      fullPath: '/student/tutor'
      preLoaderRoute: typeof AuthenticatedStudentTutorRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/teacher/analytics': {
      id: '/_authenticated/teacher/analytics'
      path: '/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof AuthenticatedTeacherAnalyticsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/courses': {
      id: '/_authenticated/teacher/courses'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/student/courses/$courseId': {
      id: '/_authenticated/student/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/quiz/$quizId': {
      id: '/_authenticated/student/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/student/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedStudentQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/teacher/courses/$courseId': {
      id: '/_authenticated/teacher/courses/$courseId'
      path: '/$courseId'
      fullPath: '/teacher/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedTeacherCoursesRoute
    }
  }
}

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentMasteryRoute: typeof AuthenticatedStudentMasteryRoute
  AuthenticatedStudentTutorRoute: typeof AuthenticatedStudentTutorRoute
  AuthenticatedStudentCoursesCourseIdRoute: typeof AuthenticatedStudentCoursesCourseIdRoute
  AuthenticatedStudentQuizQuizIdRoute: typeof AuthenticatedStudentQuizQuizIdRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentMasteryRoute: AuthenticatedStudentMasteryRoute,
  AuthenticatedStudentTutorRoute: AuthenticatedStudentTutorRoute,
  AuthenticatedStudentCoursesCourseIdRoute:
    AuthenticatedStudentCoursesCourseIdRoute,
  AuthenticatedStudentQuizQuizIdRoute: AuthenticatedStudentQuizQuizIdRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedTeacherCoursesRouteChildren {
  AuthenticatedTeacherCoursesCourseIdRoute: typeof AuthenticatedTeacherCoursesCourseIdRoute
}

const AuthenticatedTeacherCoursesRouteChildren: AuthenticatedTeacherCoursesRouteChildren =
  {
    AuthenticatedTeacherCoursesCourseIdRoute:
      AuthenticatedTeacherCoursesCourseIdRoute,
  }

const AuthenticatedTeacherCoursesRouteWithChildren =
  AuthenticatedTeacherCoursesRoute._addFileChildren(
    AuthenticatedTeacherCoursesRouteChildren,
  )

interface AuthenticatedTeacherRouteChildren {
  AuthenticatedTeacherAnalyticsRoute: typeof AuthenticatedTeacherAnalyticsRoute
  AuthenticatedTeacherCoursesRoute: typeof AuthenticatedTeacherCoursesRouteWithChildren
}

const AuthenticatedTeacherRouteChildren: AuthenticatedTeacherRouteChildren = {
  AuthenticatedTeacherAnalyticsRoute: AuthenticatedTeacherAnalyticsRoute,
  AuthenticatedTeacherCoursesRoute:
    AuthenticatedTeacherCoursesRouteWithChildren,
}

const AuthenticatedTeacherRouteWithChildren =
  AuthenticatedTeacherRoute._addFileChildren(AuthenticatedTeacherRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
